import './globals.css'
import { Inter } from 'next/font/google'
// import { NextAuthHandler } from 'next-auth/react'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Image Gallery',
  description: 'Generated by create next app',
}
function RootLayout({ children }) {
  return (
    // <NextAuthHandler>
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    // </NextAuthHandler>
  )
}
export default RootLayout;
